# docker-compose.ci.yml
version: '3'
services:
  notes_app_ci:
    container_name: notes_app_ci
    image: notes_docker-web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
    # volumes:
    #   - .:/usr/src/app
    restart: unless-stopped
